# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='board',
            old_name='contens',
            new_name='contents',
        ),
        migrations.AddField(
            model_name='board',
            name='hits',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(default='no title', max_length=200),
        ),
        migrations.AddField(
            model_name='board',
            name='tag',
            field=models.ManyToManyField(to='board.Tag'),
        ),
    ]
